wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    t:
      1:
      - 1
      4: 3.7.4
      5: 0.10.30
      8:
      - 5
activation function:
  desc: null
  value: leakyrelu
algorithm:
  desc: null
  value: MyTP
b_epochs:
  desc: null
  value: 6
b_loss:
  desc: null
  value: eye
b_sigma:
  desc: null
  value: 0.9436338799752054
batch_size:
  desc: null
  value: 188
depth:
  desc: null
  value: 4
direct depth:
  desc: null
  value: 2
epochs:
  desc: null
  value: 100
hid_dim:
  desc: null
  value: 675
in_dim:
  desc: null
  value: 784
learning_rate_for_backward:
  desc: null
  value: 0.04214781531483819
out_dim:
  desc: null
  value: 10
problem:
  desc: null
  value: classification-70000
refinement_iter:
  desc: null
  value: 12
refinement_type:
  desc: null
  value: fg
seed:
  desc: null
  value: 39
stepsize:
  desc: null
  value: 0.02239756552884841
