wandb_version: 1

b_epochs:
  value: 6
b_loss:
  value: eye
b_sigma:
  value: 0.9436338799752054
batch_size:
  value: 188
hid_dim:
  value: 675
learning_rate_for_backward:
  value: 0.04214781531483819
refinement_iter:
  value: 12
refinement_type:
  value: fg
stepsize:
  value: 0.02239756552884841
