wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    t:
      1:
      - 1
      4: 3.7.4
      5: 0.10.30
      8:
      - 5
activation function:
  desc: null
  value: leakyrelu
algorithm:
  desc: null
  value: MyTP
b_epochs:
  desc: null
  value: 8
b_loss:
  desc: null
  value: eye
b_sigma:
  desc: null
  value: 0.3386750540609912
batch_size:
  desc: null
  value: 192
depth:
  desc: null
  value: 4
direct depth:
  desc: null
  value: 2
epochs:
  desc: null
  value: 100
epochs (backward):
  desc: null
  value: 8
hid_dim:
  desc: null
  value: 551
in_dim:
  desc: null
  value: 784
learning rate (backward):
  desc: null
  value: 0.096236861563814
learning_rate_for_backward:
  desc: null
  value: 0.096236861563814
loss (backward):
  desc: null
  value: eye
out_dim:
  desc: null
  value: 10
problem:
  desc: null
  value: classification-70000
refinement iteration:
  desc: null
  value: 30
refinement type:
  desc: null
  value: gf
refinement_iter:
  desc: null
  value: 30
refinement_type:
  desc: null
  value: gf
seed:
  desc: null
  value: 39
sigma (backward):
  desc: null
  value: 0.3386750540609912
stepsize:
  desc: null
  value: 0.016422963881001652
