wandb_version: 1

b_epochs:
  value: 9
b_loss:
  value: inv
b_sigma:
  value: 0.31103770444130013
batch_size:
  value: 151
hid_dim:
  value: 663
learning_rate_for_backward:
  value: 0.019070529671368585
refinement_iter:
  value: 6
refinement_type:
  value: gf
stepsize:
  value: 0.07862464171882241
